//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orlik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using static Orlik.CodeFirstDemoEntities;

    public partial class CodeFirstDemoEntities : DbContext
    {
        public CodeFirstDemoEntities()
            : base("name=CodeFirstDemoEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ORLIK_DATABASE1> ORLIK_DATABASE1 { get; set; }

        
    }
}
