//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orlik
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORLIK_DATABASE1
    {
        public int Id { get; set; }
        public string Adress { get; set; }
        public string Name { get; set; }
        public System.DateTime Open_Hour { get; set; }
        public System.DateTime Close_Hour { get; set; }
        public string Ball { get; set; }
        public string Light { get; set; }
    }
}
